# Generated by Django 5.2.5 on 2026-01-05 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routefinder', '0001_initial'),
    ]

    operations = [
    ]
