# Generated by Django 5.2.5 on 2026-01-06 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routefinder', '0002_auto_20260105_0602'),
        ('routefinder', '0002_contribute'),
    ]

    operations = [
    ]
