# Generated by Django 5.2.5 on 2026-01-11 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routefinder', '0003_merge_0002_auto_20260105_0602_0002_contribute'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='station',
            name='lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
